In [ ]:
%pip install numpy

In [ ]:
import numpy as np
import sys

In [ ]:
print(f"Numpy Version:{np.__version__}")
print(f"Python Version:{sys.version}")

Numpy Version:2.0.2
Python Version:3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]


In [ ]:
arr=([10,20,30,40,50])
arr

[10, 20, 30, 40, 50]

In [ ]:
list1=[10,20,40,50]
print(list1)

[10, 20, 40, 50]


In [ ]:
import numpy as np
#1D array
list1=[10,20,40,50]
arr=np.array(list1)
print(arr)
print(type(arr))
print(list1)

[10 20 40 50]
<class 'numpy.ndarray'>
[10, 20, 40, 50]


In [ ]:
#2D array
list2=[[1,2,3],
       [4,5,6],
       [7,8,9]]
arr2d=np.array(list2)
print(arr2d)
print(list2)
print(type(arr2d))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'numpy.ndarray'>


In [ ]:
#Creating an array with float data type
float_arr= np.array([1,2,3], dtype=np.float64)
print(float_arr)
print(float_arr.dtype)

[1. 2. 3.]
float64


In [ ]:
#Array Attributes (methods)
my_matrix= np.array(([[1,2,3],[4,5,6]]),dtype=np.int32)

print(my_matrix)
print()
print(my_matrix.ndim)      #its give number of dimensions of an array
print()
print(my_matrix.shape)     #its give shape of an array
print()
print(my_matrix.size)      #its give size of an array
print()
print(my_matrix.dtype)     #its give datatype of an array
print()
print(my_matrix.itemsize)  #its give bytes storage in memory of an array

[[1 2 3]
 [4 5 6]]

2

(2, 3)

6

int32

4


In [ ]:
#Built in Functions for Array
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(1,5,6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#1D Array indexing
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[2])
print(arr[-1])
arr[-2]=500
print(arr)
print(arr[2:4])

10
30
50
[ 10  20  30 500  50]
[ 30 500]


In [ ]:
#2D Array indexing
matrix=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
matrix[0,1]


np.int64(20)

In [ ]:
matrix[0,:]

array([10, 20, 30])

In [ ]:
matrix[0,0:2]

array([10, 20])

In [ ]:
arr=np.zeros((3,3))
print(arr)
arr[0,0]=1
arr[1,1]=1
arr[2,2]=1
arr
arr[2,0]=1
arr[0,2]=1
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]]


In [ ]:
matrix[0:2,0:2]

array([[10, 20],
       [40, 50]])