In [ ]:
%pip install numpy

In [ ]:
import numpy as np
import sys

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr=np.array([10,20,30,40])
arr[1]

np.int64(20)

In [ ]:
data= np.array([5,12,8,21,3,14,7])
print(data>10)
data[data>10]

[False  True False  True False  True False]


array([12, 21, 14])

In [ ]:
data1= np.arange(0,21,1)
print(data1%2==0)
data1[data1%2==0]

[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
# statistical summaries
x=np.array([10,40,20,30])
print(np.mean(x))
print(np.median(x))

25.0
25.0


In [ ]:
x=np.array([
    [10.0,  200.0],
    [30.0,  100.0],
    [20.0,  300.0]
])
row_means= np.mean(x, axis=0)
print(row_means)
col_means= np.mean(x, axis=1)
print(col_means)

NameError: name 'np' is not defined

In [ ]:
flat_arr=np.arange(6)
print("Original 1D array:", flat_arr)

#reshape to 2D matrix of 2 rows and 3 columns
matrix_2d=flat_arr.reshape(2,3)
print("\nReshaped to 2x3 Matrix:\n",matrix_2d)

#flatten it back to 1d
flattened= matrix_2d.flatten()
print("\nFlattened to 1D array:",flattened)

Original 1D array: [0 1 2 3 4 5]

Reshaped to 2x3 Matrix:
 [[0 1 2]
 [3 4 5]]

Flattened to 1D array: [0 1 2 3 4 5]


In [ ]:
inputs= np.array([1.0,2.0])

weights= np.array([
    [0.2, 0.8, -0.5],
    [0.5, -0.1, 0.4]
])
print(np.dot(inputs, weights))

[1.2 0.6 0.3]


In [ ]:
celsius_list=np.array([0, 10, 25,36.6,40])
fah=((celsius_list*9/5)+32)
print(celsius_list)
print(fah)

[ 0.  10.  25.  36.6 40. ]
[ 32.    50.    77.    97.88 104.  ]


In [ ]:
student_data=np.array([
    [90, 18, 25, 85],
    [75, 14, 15, 62],
    [95, 19, 30, 92]
    [60, 10, 8, 45]
])
Attendance=[0:0]
print(Attendance)

SyntaxError: invalid syntax (1419830390.py, line 7)

In [ ]:
customer_ages=np.array([25, -1,47, 999, 18, 31, -5, 62])
new=np.where((customer_ages<0) | (customer_ages>100),30,customer_ages)
print(new)

[25 30 47 30 18 31 30 62]
